from enum import Enum


class DocumentType(str, Enum):
    DNI = "DNI"
    CUIL = "CUIL"
    CUIT = "CUIT"
    PASSPORT = "PASSPORT"
    UNKNOWN = "UNKNOWN"


class IdentityLifecycleStatus(str, Enum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    DECEASED = "DECEASED"
    INCONSISTENT = "INCONSISTENT"
    NOT_FOUND = "NOT_FOUND"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class EvidenceSourceType(str, Enum):
    IDENTITY = "IDENTITY"
    FINANCIAL = "FINANCIAL"
    LABOR_FISCAL = "LABOR_FISCAL"
    RELATIONSHIP = "RELATIONSHIP"
    DOCUMENT = "DOCUMENT"
    INTERNAL_RULE = "INTERNAL_RULE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SYSTEM = "SYSTEM"


class EvidenceQuality(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class RiskCategory(str, Enum):
    NORMAL = "NORMAL"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    FRAUD_SUSPECT = "FRAUD_SUSPECT"
    NOT_EVALUABLE = "NOT_EVALUABLE"


class RecommendationType(str, Enum):
    APPROVE = "APPROVE"
    REVIEW = "REVIEW"
    DENY = "DENY"
    ESCALATE = "ESCALATE"
    REQUEST_MORE_INFORMATION = "REQUEST_MORE_INFORMATION"
    BLOCK = "BLOCK"


class CaseProcessingState(str, Enum):
    ACCEPTED_FOR_PROCESSING = "accepted_for_processing"
    INVALID_IDENTIFIER = "invalid_identifier"
    INSUFFICIENT_INPUT = "insufficient_input"
    DAILY_LIMIT_REACHED = "daily_limit_reached"
    WAITING_FOR_ENRICHMENT = "waiting_for_enrichment"
    READY_FOR_RULES = "ready_for_rules"
    READY_FOR_REASONING = "ready_for_reasoning"
    NOT_EVALUABLE = "not_evaluable"
    EXCLUDED = "excluded"
    SCORED = "scored"


class DecisionStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    DENIED = "DENIED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"


class AuditActionType(str, Enum):
    AUTH_LOGIN = "AUTH_LOGIN"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    CASE_CREATED = "CASE_CREATED"
    CASE_VALIDATED = "CASE_VALIDATED"
    CASE_EVALUATED = "CASE_EVALUATED"
    INTEGRATION_CONSUMED = "INTEGRATION_CONSUMED"
    HARD_RULES_EXECUTED = "HARD_RULES_EXECUTED"
    REASONING_EXECUTED = "REASONING_EXECUTED"
    SCORING_EXECUTED = "SCORING_EXECUTED"
    FINAL_ASSESSMENT_GENERATED = "FINAL_ASSESSMENT_GENERATED"
    CASE_DECISION_RECORDED = "CASE_DECISION_RECORDED"
    EXPORT_REQUESTED = "EXPORT_REQUESTED"
    ADMIN_CONFIGURATION_CHANGED = "ADMIN_CONFIGURATION_CHANGED"
    INTEGRATION_CONFIGURATION_CHANGED = "INTEGRATION_CONFIGURATION_CHANGED"


class AuditResultType(str, Enum):
    OK = "OK"
    OBSERVED = "OBSERVED"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"


class ProviderType(str, Enum):
    IDENTITY = "IDENTITY"
    FINANCIAL = "FINANCIAL"
    LABOR_FISCAL = "LABOR_FISCAL"
    RELATIONSHIP = "RELATIONSHIP"
    DOCUMENT = "DOCUMENT"


class IntegrationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    DISABLED = "DISABLED"
    TESTING = "TESTING"
