IF OBJECT_ID('dbo.AF_INCREMENTAL_CONTROL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AF_INCREMENTAL_CONTROL (
        PROCESS_NAME nvarchar(100) NOT NULL CONSTRAINT PK_AF_INCREMENTAL_CONTROL PRIMARY KEY,
        ULTIMA_FECHA_PROCESADA datetime2 NOT NULL,
        ULTIMO_ID_PROCESADO bigint NOT NULL,
        ULTIMA_EJECUCION datetime2 NULL,
        ESTADO nvarchar(30) NOT NULL,
        MENSAJE_ERROR nvarchar(max) NULL
    );
END;
