IF OBJECT_ID('dbo.AF_CASE_DECISION_HISTORY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AF_CASE_DECISION_HISTORY (
        HISTORY_ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_AF_CASE_DECISION_HISTORY PRIMARY KEY,
        CASE_ID uniqueidentifier NOT NULL,
        SIN_ID bigint NOT NULL,
        ACTION_TYPE nvarchar(40) NOT NULL,
        DECISION nvarchar(30) NULL,
        FRAUDE_CONFIRMADO bit NULL,
        USUARIO nvarchar(120) NOT NULL,
        COMENTARIO nvarchar(max) NULL,
        FECHA_ACCION datetime2 NOT NULL,
        CONSTRAINT FK_AF_CASE_DECISION_HISTORY_CASE_ID
            FOREIGN KEY (CASE_ID) REFERENCES dbo.AF_MONITORED_CASES (CASE_ID) ON DELETE CASCADE
    );

    CREATE INDEX IX_AF_CASE_DECISION_HISTORY_SIN_ID_FECHA_ACCION
        ON dbo.AF_CASE_DECISION_HISTORY (SIN_ID, FECHA_ACCION DESC);
END;
