IF OBJECT_ID('dbo.AF_MONITORED_CASES', 'U') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID('dbo.AF_MONITORED_CASES')
          AND name = 'IX_AF_MONITORED_CASES_PRIORITY_DATE'
   )
BEGIN
    CREATE INDEX IX_AF_MONITORED_CASES_PRIORITY_DATE
        ON dbo.AF_MONITORED_CASES (PRIORIDAD_ORDEN DESC, FECHA_ULTIMA_EVALUACION DESC);
END;
