IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.SINIESTROS')
      AND name = 'IX_SINIESTROS_SIN_FECAUD_SIN_ID'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_SINIESTROS_SIN_FECAUD_SIN_ID
        ON dbo.SINIESTROS (SIN_FECAUD ASC, SIN_ID ASC);
END;
